import turtle as tut

tut.pensize(10)

tut.color('blue')
tut.penup()
tut.goto(-110,-25)
tut.pendown()
tut.circle(45)
tut.penup()
tut.goto(0,-25)
tut.color('black')
tut.pendown()
tut.circle(45)
tut.penup()
tut.goto(110,-25)
tut.color('red')
tut.pendown()
tut.circle(45)
tut.penup()
tut.goto(-55,-75)
tut.color('yellow')
tut.pendown()
tut.circle(45)
tut.penup()
tut.goto(55,-75)
tut.color('green')
tut.pendown()
tut.circle(45)
