import turtle
import Lab3_Maze
turtle=turtle.Turtle()
turtle.penup()
turtle.goto(20,-180)
turtle.pendown()
turtle.shape('turtle')
turtle.color("#DB148E")
turtle.width(5)
turtle.left(90)

turtle.forward(75)
turtle.right(90)
turtle.forward(125)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(125)
turtle.right(90)

turtle.forward(70)
turtle.right(90)
turtle.forward(125)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(125)
turtle.right(90)

turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(70)

                
